[package]
name = "picovm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kvm-bindings = "0.6.0"
kvm-ioctls = "0.15.0"
libc = "0.2.150"
vm-memory = "0.13.1"
vmm-sys-util = "0.11.2"
